/**
 * Central password policy. Used by change-password, complete-reset, and
 * any future account-creation paths that accept a user-chosen password.
 * Temp credentials generated by admins are NOT subject to this policy
 * (they are short-lived and force a change on first use).
 */
const MIN_LENGTH = 10;
const MAX_LENGTH = 128;

function validatePasswordStrength(password) {
  if (typeof password !== 'string') {
    return { ok: false, message: 'Password must be a string.' };
  }
  if (password.length < MIN_LENGTH) {
    return {
      ok: false,
      message: `Password must be at least ${MIN_LENGTH} characters.`,
    };
  }
  if (password.length > MAX_LENGTH) {
    return {
      ok: false,
      message: `Password must be at most ${MAX_LENGTH} characters.`,
    };
  }
  if (!/[a-z]/.test(password)) {
    return { ok: false, message: 'Password must contain a lowercase letter.' };
  }
  if (!/[A-Z]/.test(password)) {
    return { ok: false, message: 'Password must contain an uppercase letter.' };
  }
  if (!/[0-9]/.test(password)) {
    return { ok: false, message: 'Password must contain a number.' };
  }
  // Reject a small set of extremely common passwords (not a full breach list).
  const lower = password.toLowerCase();
  const common = [
    'password', 'password1', 'password123', '1234567890', 'qwertyuiop',
    'admin12345', 'letmein123', 'welcome123', 'changeme12',
  ];
  if (common.some((c) => lower.includes(c))) {
    return { ok: false, message: 'Password is too common. Choose something harder to guess.' };
  }
  return { ok: true };
}

module.exports = { validatePasswordStrength, MIN_LENGTH, MAX_LENGTH };
